### ISSUE TITLE
Possible archival of repository?

### ISSUE THREAD

**Issue by cwaldren-ld** [softprops/launchdarkly#1]
Hi @softprops, 

I am employed by LaunchDarkly and wanted to ask if you'd be willing to archive this repository. 

We've just put out the first stable release of the [LaunchDarkly Rust Server SDK](https://github.com/launchdarkly/rust-server-sdk), and are looking to avoid any confusion over where the supported SDK lives.

**Comment by softprops** [comment]
absolutely. and glad to see this finally happened for real! Ill add a note in the readme
